theme: jekyll-theme-architect
title: Adam Stone's Digital Portfolio
description: Digital Portfolio of Adam Stone's Creations!

lsi: false
safe: true
source: ['/docs']
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge